# Generated by Django 3.0.2 on 2020-02-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='alga',
        ),
    ]
